name: Deploy Storybook

on:
  push:
    branches: ['dev', 'main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          yarn install --immutable --immutable-cache --check-cache

      - name: Build Storybook
        run: |
          yarn build-storybook

      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: storybook-deploy
